name: 'Get README.md Version'
description: 'Set README.md file version'
branding:
  icon: 'tag'
  color: 'gray-dark'
inputs:
  version:
    description: 'version# to set'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
